http:
  routers:
    traefik:
      rule: Host(`traefik.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - https
      service: api@internal
      middlewares:
        - chain-basic-auth
      tls:
        certResolver: ovh
