# traefik/traefik.yml
global:
  checkNewVersion: true

api:
  insecure: false
  dashboard: true

log:
  level: INFO # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  format: common
  filePath: /logs/traefik.log

accessLog:
  filePath: /logs/access.log
  bufferingSize: 100 # Configuring a buffer of 100 lines
  filters:
    statusCodes: "204-299,400-499,500-599"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"

ping:
  entryPoint: ping

providers:
  docker:
    exposedByDefault: false
    watch: true
    endpoint: unix:///var/run/docker.sock # Use Docker Socket Proxy instead for improved security
    # endpoint: tcp://socket-proxy:2375
    # Automatically set Host rule for services
    # defaultrule: "Host(`{{ index .Labels \"com.docker.compose.service\" }}.$DOMAIN_NAME`)"
    network: proxy
    # swarmMode: false
  file:
    directory: /rules # Load dynamic configuration from one or more .toml or .yml files in a directory
    watch: true # Only works on top level files in the rules folder
    # filename: /path/to/file # Load dynamic configuration from a file

# metrics:
#   prometheus:
#     buckets: "0.1,0.3,1.2,5.0"

